all:
	g++ -std=c++2a src/main.cpp imgui/*.cpp imgui/backends/imgui_impl_glfw.cpp imgui/backends/imgui_impl_opengl3.cpp src/glad.c -Iinclude -Iinclude/imgui -lglfw -lGL -lX11 -lpthread -lXrandr -lXi -ldl -lm
